- .eslintrc.json
- .gitignore
- Session/Session.js
- SessionsManager/SessionsManager.js
- browser/browser.js
- driver/pluma-webdriver.js
- index.js
- package-lock.json
- package.json
- pluma-selenium-client/pluma-selenium-client.js
- scripts/run_test.sh
- standalone-driver/standalone_driver.js
- tests/createSession.js
- tests/create_deleteSession.js
- tests/getTitleTest.js
- tests/navigateToUrlTest.js
merging code from private repo.
> merging code from private repo

- SessionsManager/SessionsManager.js
- driver/pluma-webdriver.js
- index.js
delete session endpoint had not been updated and is not functional with findSession function inside SessionsManager
> fixed deleteSession endpoint

- package-lock.json
- package.json
- standalone-driver/standalone_driver.js
added functionality for user provided port in which to start the server. The code in standalone_driver.js will become what is compiled into the executable for each platform using pkg
> add option for user provided port

- .github/ISSUE_TEMPLATE/refactoring.md
- Added a template for issues related to refactoring.
> feat: add refactoring issue template

- src/Error/NoSuchWindow.ts
- Fixed inheritance structure for this error.
Closes #53
> refactor: changed NoSuchWindow to inherit from NotFoundError

- commitlint.config.js
- Allows for longer commit messages.
> feat: increase commitlint max header length

- src/Error/JavaScriptError.ts
- src/Error/ScriptTimeout.ts
- src/Error/errors.ts
- added above classes to `Error` folder (to be later used in execute script sync endpoint logic)
- progress toward #66
> feat: add JavaScriptError and ScriptTimeoutError classes

- src/app.ts
- src/index.ts
- moved logic not needed to start server to `app.ts`.
- this change is needed to simplify future testing.
> refactor: separated app logic from server logic

- .vscode/launch.json
- simplifies debugging by only running tests pertaining to the active file.
> test: jest only runs tests on active file in debug mode

- test/jest/e2e/is-displayed.test.js
- adds tests for `isDisplayed` endpoint
- tests for human visibility of elements based on [recommendation](https://www.w3.org/TR/webdriver1/#element-displayedness)
- tests if Selenium requests are redirected properly
> test: isDisplayed e2e

- test/jest/e2e/session.test.js
- adds tests for creating a session.
- some are expected to fail at the moment. New issues have been created for them.
> test: add session tests

- .eslintignore
- package.json
- fixed npm `lint` script, and added `lint:fix`
- updated `.eslintignore`
> fix: correct npm lint scripts

- README.md
- added new information and condensed older content.
- added a section explaining how to use PlumaDriver without Selenium
- fixed broken links
- fixed instructions for building the executable
Please let me know if you can follow these instructions, and perhaps attempt to create a Session using PlumaDriver.
[Here is a direct link.](https://github.com/Seneca-CDOT/plumadriver/blob/feat/update-readme/README.md)
> docs: update readme instructions and content

- package-lock.json
- package.json
- Minor update to package files to reflect version change.
> chore(version): update package.json to v0.6.0

- .circleci/config.yml
- package.json
- test/jest/e2e/navigation.test.js
- test/jest/e2e/session.test.js
- test/jest/e2e/timeouts.test.js
Added CI to repo and skipping failing tests until the issues related to those tests are addressed.
> Closes #99. Add Continuous Integration

- package-lock.json
- package.json
- src/Session/Session.ts
- updates jsdom to the latest version: 16.0.1
- fixes bug in execute script after update.
> chore: update jsdom

- README.md
- adds information about which options can be set when creating a WebDriver instance.
> docs: add PlumaDriver options

- .circleci/config.yml
Initial addition of circleci to plumadriver's ci.
This can be expanded or improved in the future.
> ci: add CircleCI for windows

- README.md
- removes whitespace and note in the introduction.
> docs: fix formatting and remove note in intro

- src/Session/Session.ts
WIP. This is actually gonna take a while to go through.
> refactor: remove explicit Promise return in Session process Function

- package-lock.json
- package.json
- new tag, and package.json updates.
> chore(version): update to v0.7.0

- src/WebElement/WebElement.ts
- test/jest/WebElement/WebElement.test.js
- test/jest/WebElement/pages/button.html
- Elements will now attempt to be focused (i.e. made the active element) when clicked
> fix: focus elements on click

- package-lock.json
- package.json
- updated package version and added tag.
> chore: update to version 0.9.0

- README.md
- minor update to docs to include recently completed endpoint.
> docs: add Get Active Element to completed endpoints

- package-lock.json
- package.json
- Adds non-breaking updates to packages to address security issues.
> chore: update jsdom and vulnerable depedencies

- src/Session/Session.ts
- src/SessionManager/SessionManager.ts
- src/WebElement/WebElement.ts
- src/app.ts
- src/index.ts
- src/logger.ts
- src/routes/cookies.ts
- src/routes/elements.ts
- src/routes/index.ts
- src/routes/navigate.ts
- src/routes/timeouts.ts
- src/utils/utils.ts
- tsconfig.json
- edited `tsconfig.ts` settings to enable default imports (Closes #45).
- changed namespace imports to default imports where available.
> refactor: convert namespace imports to default imports

- test/jest/e2e/active-element.test.js
- test/jest/e2e/click.test.js
- test/jest/e2e/cookies.test.js
- test/jest/e2e/execute-script-sync.test.js
- test/jest/e2e/get-page-source.test.js
- test/jest/e2e/helpers.js
- test/jest/e2e/is-displayed.test.js
- test/jest/e2e/navigation.test.js
- test/jest/e2e/switch-to-frame.test.js
- test/jest/e2e/timeouts.test.js
- Checks for status codes for all supertest requests. (Closes #109)
> test: add status codes to supertest requests

- package-lock.json
- package.json
- changed version in package files.
> chore: update to version 0.10.1

- tsconfig.json
- Optimizes build times and reduces executable size by choosing a modern ECMAScript target.
> perf: change build target to ESNext

- src/Session/Session.ts
- test/jest/e2e/session.test.js
> fix: matching capabilities giving wrong result

- src/Browser/Browser.ts
- src/Browser/BrowserConfig.ts
- src/Error/WebDriverError.ts
- src/Session/Session.ts
- tsconfig.json
Addressed the strictPropertyInitialization task in #32 
Initialized variable and added the assignment assertion operator to support strictPropertyInitialization.
> refactor: enable strictPropertyInitialization

- package-lock.json
- package.json
- src/Browser/Browser.ts
- src/Browser/BrowserConfig.ts
- src/CapabilityValidator/CapabilityValidator.ts
- src/Error/WebDriverError.ts
- src/Session/Session.ts
- src/SessionManager/SessionManager.ts
- src/Types/types.d.ts
- src/WebElement/WebElement.ts
- src/app.ts
- src/logger.ts
- src/utils/utils.ts
- tsconfig.json
Solved most of the `noImplicitAny` subtask in #32 
I've given many parameters specific types and typed a few variables as any (no idea what type to give them) in order to support the `noImplicitAny` rule. This pull request doesn't solve all errors since there's still a few things that need to be fixed (a few libraries need to be installed and @pynnl will be handling the rest of `Session.ts`) so I will save those for a separate pull request. The noImplicitAny rule will be false for the time being.
My changes aren't exactly perfect so I am hoping for some feedback before this gets added to master. I'll be happy to make any requested changes as soon as possible.
> refactor: Added noImplicitAny Support

- 5.0.0-alpha.8
- package-lock.json
- package.json
- src/Types/types.d.ts
- src/routes/cookies.ts
- src/routes/elements.ts
- src/routes/index.ts
- src/routes/navigate.ts
- src/routes/timeouts.ts
- src/utils/utils.ts
Extended the Router class to change the request types to avoid unnecessary null checks
Closes #209
> refactor: extended express router to change request type
