- .eslintrc.json
- package-lock.json
- package.json
Note: `eslint/explicit-function-return-type` has been temporarily disabled until #32 is completed.
Closes #35.
> fix: vulnerable packages with npm audit

- package.json
- Add `node_modules` to `modulePathIgnorePatterns` in `Jest` config.
> fix: exclude node_modules in Jest tests

- src/Error/InternalServerError.ts
- src/Error/SessionNotCreated.ts
- src/Error/UnableToSetCookie.ts
- src/Session/Session.ts
- fix formatting in `SessionNotCreated` and `InternalServerError`
- replace throwing `InternalServerError` with `SessionNotCreated` when failed to create session.
> fix: session and internal error classes

- src/Session/Session.ts
- src/WebElement/WebElement.ts
- returns `null` in `undefined` value cases (Closes #20).
- throws `JavaScriptError` and `ScriptTimeout` when appropriate (Closes #72).
- fixes error accessing global `document` and `window` objects (Closes #69).
- serializes `HTMLElement` objects in the correct format (Closes #73).
- refactored and optimized `executeScript` logic. (Closes #66)
Test: `npm run test:compile`
> fix: executeScript endpoint

- src/Browser/Browser.ts
- detect 401 errors and create a new jsdom instance in those cases with current config settings.
- preserve `CookieJar` values.
Test: `npm run test:compile`
> fix: jsdom crashing on 401 errors

- .lintstagedrc.json
- allows linting of typescript files. Safe to re-enable with new linting rules.
> feat: enable lint-staged to run eslint against .ts files

- src/Session/Session.ts
- test/jest/execute-script-sync.test.js
- scripts now called using Jsdom's `window.eval` in order to have access to global functions.
- added test for global functions. Improved old Promise test.
Test: `npm run test:compile`
Closes #77.
> fix: global functions not recognized when executing script

- src/Browser/Browser.ts
- src/Error/NoSuchCookie.ts
- src/Error/errors.ts
- src/Session/Session.ts
- src/Types/types.d.ts
- src/routes/cookies.ts
- test/jest/get-named-cookie.test.js
- adds ability to retrieve a cookie by name in the context of the current active document.
- fixed express logic to handle `name` route param.
- created `NoSuchCookie` error.
- added tests for endpoint.
- some diffs are due to `prettier` formatting.
Closes #84.
> feat: Get Named Cookie endpoint

- src/Browser/Browser.ts
- src/Session/Session.ts
- src/routes/cookies.ts
- test/jest/delete-cookie.test.js
- added `Delete Cookie` endpoint (Closes #86).
- added `Delete All Cookies` endpoint (Closes #85).
- added tests (`npm run test:compile`).
- some diffs were needed to make older code pass typescript linting rules. (progress toward #32).
> feat: delete cookie endpoints

- src/logger.ts
- removes clutter in the console when running `e2e` tests (logs will still be found in `pluma-logs`).
> fix: remove winston logging to the console during tests

- src/SessionManager/SessionManager.ts
- fixes small typo in property wording on line 50: changed `Pomt` to `Prompt` (Closes #78).
- rest of the diffs are from `prettier` formatting.
> fix: correct typo in unhandledPromptBehaviour

- src/Session/Session.ts
- Fixes how `execute script` responses are handled. 
- Fixes error when processing certain falsy values (Closes #79).
Note: some tests will fail since they expect the old format. This will be fixed by #96.
> fix: change execute script return value in session process

- src/Session/Session.ts
- test/jest/e2e/execute-script-sync.test.js
- `NodeList` and `HTMLCollection` objects are converted to arrays before they are handled.
- added new tests for this bug: `npm run compile && npm test e2e/execute-script`
Closes #104
> fix: correct NodeList and HTMLCollection handling in execute script

- src/index.ts
This line appears to have no purpose. Reading `process.env` variables also carries a performance penalty so it is best we remove this.
> refactor: remove unnecessary NODE_ENV assignment

- src/routes/index.ts
- test/jest/e2e/shutdown.test.js
- Adds an endpoint (non-W3C) used by Selenium to shutdown a driver instance.
- Fixes #116. Process will no longer exit due to an empty sessions list.
Test: `npm run compile && npm test e2e/shutdown`
> feat: shutdown endpoint

- commitlint.config.js
- package-lock.json
- package.json
- adds [Commitizen](https://github.com/commitizen/cz-cli), a tool for formatting commit messages.
- useful for newcomers to the repo who are unfamiliar with the standard `commitlint` format.
Test: try to commit a change with `npm run commit`
> feat: add commitizen package, configs, and scripts

- .lintstagedrc.json
- fixed bug where `.md` files would be evaluated by non-existent `markdownlint`.
> fix: error in lintstaged config affecting markdown files

- bin.js
- the `plumadriver` variable is not needed when building with `pkg`
- this prevents running into a linter error with `npm run lint`
> refactor: remove unnecessary constant variable in bin.js

- package-lock.json
- package.json
- src/Session/Session.ts
- src/SessionManager/SessionManager.ts
- src/utils/utils.ts
- test/jest/e2e/session.test.js
- test/jest/utils/utils.test.js
This fixes #113, adding a new module `utils/version`, which exposes a `getVersion()` function to return a `String` of the form `v0.5.0`.  Because this needs to include version info from `package.json`, which is outside the `rootDir`, I needed a workaround to load this file at compile time.  Different projects do this in different ways (e.g., [Facebook uses `require()` in Jest](https://github.com/facebook/jest/blob/master/packages/jest-core/src/version.ts)), but I opted for using a dependency-free module ([psjon](https://github.com/serkanyersen/pjson)) that does exactly what I wanted without needing to modify a lot of your config.
NOTE: the tests are broken for me, so I can't fully test this locally--all tests fail with:
```
● Test suite failed to run
The name `tough-cookie` was looked up …
```
> fix: use package.json version for browserVersion

- package.json
Fixes #89, updating compile script invocation from `compile-ts` to `compile`.
One note for the future: devs on Windows may have problems with `&&` in npm scripts.  It's better to use [npm-run-all](https://www.npmjs.com/package/npm-run-all), which exposes `run-s` and `run-p` for sequential or parallel running of multiple scripts, giving a cross-platform way to do `&&` safely.
> fix: update compile command in npm watch script

- src/Session/Session.ts
- test/jest/e2e/execute-script-sync.test.js
- fixes #107: error caused by attempting to return newline in execute script sync.
Test: `npm test e2e/execute`
> fix: correct returning newlines in execute script sync

- src/Session/Session.ts
- test/jest/e2e/execute-script-sync.test.js
- Recommend reverting this for the time being. While this fixes newline character return values, it causes errors in some scripts where newlines are used for spacing by Selenium.
> Revert "fix: correct returning newlines in execute script sync"

- CONTRIBUTING.md
- Adds the missing commit message types to `CONTRIBUTING.md`
> docs: add missing commit types

- src/Browser/BrowserConfig.ts
- test/jest/e2e/inject-api.test.js
- adds stubs for `scrollIntoView`, `getBBox`, and `navigationStart`.
- added test for the injector.
- prettier diffs.
> feat: add injector for missing jsdom apis

- src/WebElement/WebElement.ts
- test/jest/e2e/click.test.js
- stops click events from bubbling when the element has a label element as an ancestor. (workaround for this [jsdom bug](https://github.com/jsdom/jsdom/issues/2717)).
- added tests for click bubbling.
> fix: call stack error in jsdom when clicking label element descendants

- src/Browser/Browser.ts
- src/Session/Session.ts
- replaced generic `this.dom.window` lookups to instead return the active browsing context window.
- prerequisite for #159: multiple Window objects from different browsing contexts will need to be handled, as well as the ability to store which window is "active". Therefore, we can no longer use `this.dom.window` for every case.
> refactor: support current browsing context

- src/Browser/Browser.ts
- src/Error/StaleElementReference.ts
- src/Error/errors.ts
- src/Session/Session.ts
- test/jest/e2e/find-element.test.js
- added `StaleElementReference` error class.
- fixed logic to throw this error in element endpoints whenever an element that is not connected to the DOM is accessed.
- added test for stale element checks
Closes #160.
> fix: add missing checks for stale element reference errors

- src/Session/Session.ts
Fixes spelling error in Session.ts (Closes #128).
> refactor: fix spelling mistake in capabilities naming

- src/Session/Session.ts
- test/jest/e2e/timeouts.test.js
- Changes default pageLoad value to 300000 as indicated in the spec. (Closes #93)
- Unskipped relevant test.
> fix: pageLoad default timeout

- package-lock.json
- package.json
- src/CapabilityValidator/CapabilityValidator.ts
- src/Session/Session.ts
- src/WebElement/WebElement.ts
- src/utils/utils.ts
- Uses a stored lookup of `Object.hasOwnProperty.call` (Closes #47).
- Some diffs are from prettier formatting.
> refactor: replace Object hasOwnProperty calls with 'has' package

- src/Session/Session.ts
- src/SessionManager/SessionManager.ts
- fixes acceptInsecureCerts not being set to the value passed in the request (Closes #112).
> fix: acceptInsecureCerts not being set properly

- src/Browser/Browser.ts
- src/Browser/BrowserConfig.ts
- src/CapabilityValidator/CapabilityValidator.ts
- src/Session/Session.ts
- src/SessionManager/SessionManager.ts
- src/Types/types.d.ts
- src/constants/constants.ts
- src/utils/utils.ts
- test/jest/e2e/session.test.js
- Renamed `behaviour` to `behavior` to match client requests according to spec.
- Unskipped `alwaysMatch` session test.
- Added logic to handle `ignore` cases. (Closes #111)
> fix: unhandledPromptBehavior not working in 'ignore' cases

- src/CapabilityValidator/CapabilityValidator.ts
- src/routes/timeouts.ts
- test/jest/e2e/timeouts.test.js
- fix validation logic for timeouts (Closes #92).
- fix endpoint return value in express.
- unskip timeout test.
> fix: set timeout endpoint not accepting zero values

- README.md
- Adds reference link back to spec for every endpoint that has been completed.
Closes #131.
> docs: add links to W3C spec for completed endpoints

- src/Session/Session.ts
- test/jest/capability-validator.test.js
- Replaced type checking performed with the constructor name (Closes #34).
> refactor: replace constructor name checks

- src/Session/Session.ts
- src/utils/utils.ts
- test/jest/e2e/navigation.test.js
- Removes `null` responses, and ensures all JSON responses have a `value` property (Closes #91).
- Unskips { value: null } test.
> fix: return { value: null } in cases where response was null

- src/Browser/Browser.ts
- src/Session/Session.ts
- test/jest/e2e/cookies.test.js
- Fixed async cookie operations not being handled properly.
- Refactored naming of cookie functions for better clarity.
- Added test for associated cookie retrieval.
Closes #87.
> fix: get all cookies endpoint returning unassociated cookies

- .eslintignore
- .eslintrc.json
- package.json
- src/Browser/Browser.ts
- src/Browser/BrowserConfig.ts
- src/Browser/CookieValidator.ts
- src/CapabilityValidator/CapabilityValidator.ts
- src/Session/Session.ts
- src/SessionManager/SessionManager.ts
- src/Types/types.d.ts
- src/WebElement/WebElement.ts
- src/app.ts
- src/constants/constants.ts
- src/routes/elements.ts
- src/utils/utils.ts
- Adds missing return types from functions.
- Adds missing interfaces and types for many variables and objects.
- Fixes linter script not working properly in `npm test`.
Progress toward #32.
> style: fix missing types and return values in typescript

- .circleci/config.yml
The `CircleCI` windows build fails when all the weekly credits have been used. 
To avoid this problem, this PR disables the windows build.
> chore: disable CircleCI windows build

- package-lock.json
- package.json
- src/Browser/Browser.ts
- src/Session/Session.ts
- src/Types/types.d.ts
Updating TypeScript is neccessary for #32, for example:
- Different type definitions such as `Element.ownerDocument` is type of `Document | null` in the old version, but `Document` in the new one.
- Provides more features such as `@ts-expect-error`
P/S: you'll get some warnings when doing linting, but those will be fixed along with #32 as they are all about untyped variables.
> chore: update typescript

- .eslintrc.json
- package-lock.json
- package.json
- src/Browser/Browser.ts
- src/Browser/BrowserConfig.ts
- src/Session/Session.ts
- src/Types/types.d.ts
- src/constants/constants.ts
- tsconfig.json
> refactor: enable some strict options, add type for jsdom/express

- src/Browser/Browser.ts
- src/Browser/CookieValidator.ts
- src/Session/Session.ts
- src/Types/types.d.ts
- src/WebElement/WebElement.ts
- src/routes/cookies.ts
- src/routes/elements.ts
- src/routes/index.ts
- src/routes/timeouts.ts
- tsconfig.json
Solved the `strictNullChecks` subtask in  #32 .
strictNullChecks @zthaver
Changed function return types and created new types necessary in order to support `strictNullChecks` in order to support typescript **strict mode**.
> refactor: enable strictNullChecks

- package-lock.json
- package.json
- src/Browser/Browser.ts
- src/Browser/BrowserConfig.ts
- src/CapabilityValidator/CapabilityValidator.ts
- src/Session/Session.ts
- src/Types/types.d.ts
- src/Types/untyped-modules.ts
- src/WebElement/WebElement.ts
- src/app.ts
- src/constants/constants.ts
- src/logger.ts
- src/routes/cookies.ts
- src/routes/elements.ts
- src/routes/index.ts
- src/routes/timeouts.ts
- src/utils/StringUnion.ts
- src/utils/utils.ts
- tsconfig.json
What this PR does:
- Enable strict mode on temporarily disabled files in #202 
- Fix eslint warning (`explicit any` and `non-null assertion`)
- Remove most explicit casting
- Combine strict options into single `strict: true` to make sure the tests pass
- Fix some minor mistakes
close #32, close #199
> refactor: clean up enabling strict mode
